<a href="https://colab.research.google.com/github/muhxz3/Pandas-Notebook/blob/main/pandasDemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
python_scores = {
    "Riya": 43, "Fiza": 38, "Saurab":37
}

s = pd.Series(python_scores)

In [3]:
s

Riya      43
Fiza      38
Saurab    37
dtype: int64

In [5]:
print(type(s))

<class 'pandas.core.series.Series'>

In [6]:
cars = {
    "name": ["Benz","MG","Audi","Merc"],
    "rating": [6,7,8,9]
}

df = pd.DataFrame(cars)

In [7]:
df

   name  rating
0  Benz       6
1    MG       7
2  Audi       8
3  Merc       9

In [9]:
# create a dataframe from a numpy array

import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
df = pd.DataFrame(a)
df

   0  1
0  1  2
1  3  4
2  5  6

In [10]:
print(df.to_numpy())

[[1 2]
 [3 4]
 [5 6]]

In [13]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [16]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv",usecols=["longitude"])

df.to_csv("new_file.csv")